package exception_handling;

public class TryFinally {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		System.out.println("Exception Handling Test Initiated");
		try
		{
			int i=1/1;
		}
		
		catch(ArithmeticException e){
			System.out.println("alert :Your Input is Wrong"+ e.getMessage());
		}
	}

}
