package exception_handling;

public class TryCatchTest {

	public static void main(String[] args) {
		
		System.out.println("Exception Handling Test Initiated");
		try
		{
			int i=1/0;
		}
		
		System.out.println("Exception Hanling Test Completed");

	}

}
